version: "3.7"

services:

  ims:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0:80
    environment:
      C_FORCE_ROOT: "true"
    ports:
      - "8000:80"
    volumes:
      - ./:/main
