# Generated by Django 4.1.5 on 2023-02-03 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('hero_img', models.ImageField(upload_to='sevice/pics')),
                ('desc', models.TextField()),
                ('benefits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=4)),
                ('solution', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=4)),
            ],
        ),
    ]
