# Generated by Django 4.1.5 on 2023-02-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='service',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.AlterField(
            model_name='service',
            name='hero_img',
            field=models.ImageField(blank=True, upload_to='sevice/pics'),
        ),
    ]
