# Generated by Django 4.1.5 on 2023-01-13 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='type',
            field=models.CharField(default=45456, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=4),
        ),
        migrations.AlterField(
            model_name='service',
            name='solution',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=4),
        ),
    ]
