# Generated by Django 4.1.5 on 2023-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='job',
            field=models.CharField(default='Developer', max_length=200),
        ),
    ]
